name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  updateFolder:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run commands to clone the new github repository
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: webpong.net
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          pkill node
          sudo rm -rf ~
          sudo git clone https://github.com/johnathanmitri/Web-Pong ~
          nohup node ~/server.mjs > output.log 2> error.log < /dev/null &
