name: Update Apache Web Folder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  updateFolder:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run commands to clone the new github repository
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: groupup.pro
        username: ec2-user
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          pkill node
          sudo rm -rf /var/www/html/CS3800-Project
          sudo git clone https://github.com/johnathanmitri/Web-Pong /var/www/html/CS3800-Project
          nohup node /var/www/html/CS3800-Project/server.mjs > output.log 2> error.log < /dev/null &
